# Generated by Django 2.0.3 on 2018-04-22 09:40

import django.contrib.auth.models
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=30)),
                ('gender', models.BooleanField(default=True)),
            ],
            bases=(django.contrib.auth.models.AnonymousUser, models.Model),
            managers=[
                ('objects', reservation.models.ReservationHostManager()),
            ],
        ),
    ]
