# Generated by Django 2.0.3 on 2018-04-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180423_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhost',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='reservationhost',
            name='date_canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationhost',
            name='date_checked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
