# Generated by Django 2.0.3 on 2018-04-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20180427_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationhost',
            name='date_checked',
        ),
    ]
