# Generated by Django 2.0.3 on 2018-05-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20180503_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationhost',
            name='christian_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservationmember',
            name='christian_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
