# Generated by Django 2.0.3 on 2018-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
