# Generated by Django 2.0.3 on 2018-03-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180329_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['pk']},
        ),
    ]
