# Generated by Django 2.0.3 on 2018-04-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180330_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
